services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=siruchat'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=siru'
    ports:
      - '3306:3306'

  redis:
    hostname: redis
    container_name: redis
    image: redis:6.2.6
    command: redis-server --requirepass siruchat --port 6379
    ports:
      - 6379:6379